version: "3"

services:
  app:
    build:
      context: .
    networks:
      - challenge-network
    container_name: app
    tty: true
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-network
  proxy:
    build: ./nginx
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
